### ISSUE TITLE
ctrlp window does not highlight match

### ISSUE THREAD

**Issue by hjdivad** [dsawardekar/ember.vim#2]
With a standard ctrl-p window, the matching portion of each line is highlighted.  This does not happen for the ember ctrl-p extensions (eg finding by model).

It occurs to me the root problem is likely in portkey, and not ember.vim.

**Comment by dsawardekar** [comment]
Ah! I think you may be referring to matching characters. Not sure if this is possible with CtrlP extensions. Will confirm.

**Comment by dsawardekar** [comment]
@hjdivad I've filed an issue with ctrlp about this at kien/ctrlp.vim#498. I'll revisit this after a confirmation that this is currently possible with CtrlP extensions.

**Comment by hjdivad** [comment]
@dsawardekar yeah now that you mention it I haven't seen highlighting in other extensions either.  ctrlp docs make it sounds like there are highlight groups available: maybe the issue is one of the filetype for the buffer?

**Comment by dsawardekar** [comment]
@kien just clarified that this feature isn't currently supported for anything other than `file` based paths. See the above the thread for more details and a suggested PR at kien/ctrlp.vim#488.

I'll leave this open to keep this on the radar, as it's useful to have.

**Comment by hjdivad** [comment]
@dsawardekar makes sense.  It's not really a huge issue: the great thing about the mappings `ember.vim` creates is that the list is already greatly narrowed, so the utility of highlighting is much less than in the normal ctrlp case of searching all files.
