### ISSUE TITLE
ember:custom Not Loading Custom Ember Syntax Highlighting

### ISSUE THREAD

**Issue by mutewinter** [dsawardekar/ember.vim#3]
I'm unable to get custom syntax highlighting for ember working with [my cutsom portkey.json](https://github.com/mutewinter/tapas-with-ember/blob/master/portkey.json#L2) using `"portkeys": ["ember:custom"],`. If I change this line to `"portkeys": ["ember:classic-coffee"]`, I get the proper syntax highlighting, but it overwrites the templates from my custom config (e.g. `Emodel post!`).

Here' my `:PortkeyVersion`:

```
Portkey: version=0.1.7
Current Resource Type: route
Portkeys Loaded:
1. tapas-with-ember/portkey.json
```

from: https://twitter.com/_dsawardekar/status/395410705945354242

**Comment by dsawardekar** [comment]
Hmm, that's odd. I was expecting the resource type to be `unknown`. This looks like something else. 

Edit: Ok I've tried this out, it's a little hard to replicate. If you have dev plugins like SyntaxAttr installed, could you post the syntax group you get under the cursor?

**Comment by dsawardekar** [comment]
I wasn't doing the right thing when loading `:custom` extensions. [Fixed](https://github.com/dsawardekar/portkey/commit/1eda05c74957b06ebfc9e75c45e97af262b5a126) in Portkey 0.1.9.

About the syntax highlighting, my initial plan was to extract keywords from ember documentation. But that was a little overwhelming. Using all keywords from the docs resulted in the entire file looked like it was painted with colors! 

So I went about picking keywords semi-manually. If you find keywords are missing send me a PR. The syntax highlighting is in [emberjs.vim](https://github.com/dsawardekar/ember.vim/blob/develop/syntax/emberjs.vim).

**Comment by mutewinter** [comment]
@dsawardekar thanks for the fix, it's working great! I'll send a PR when I find missing keywords. Are you interesting in having keywords from [Ember Data](https://github.com/emberjs/data)?

**Comment by dsawardekar** [comment]
@mutewinter Yeah, anything Ember related is fine. The syntax is stock `Viml` not `Riml` so any syntax defs derived from other languages would also work. 

Also note, currently I've kept both the Javascript and Coffeescript syntaxes in `emberjs.vim`. I'd be happy to break these out into individual files if either language needs different syn regions.
