### ISSUE TITLE
keystrokes

### ISSUE THREAD

**Issue by ghost** [dsawardekar/ember.vim#5]
Is there a video or a cheat sheet which shows the characters to type or select to switch between {model, controller, route, template, component, view}? Also how do you get Ctrl-P show the list of files vertically on a left side-bar? Thanks for the answers.

**Comment by dsawardekar** [comment]
The `<LocalLeader><LocalLeader>` will show a list of mappings made by the plugin. My leader is `;`. So `;;` gives me a list like this,

``` log
;cm       component
;cn       controller
;a        app
;r        route
;s        stylesheet
;ts       test
;tm       template
;v        view
;g        grunt
;h        helper
;m        model
```

Each of these mappings will open a Ctrl-P window with the corresponding resource. With my semi-colon mapping that's, `;m` for models, `;v` for views, etc. You can change the mapping with the `mapping` key in `portkey.json`.

I'm not sure about configuring the Ctrl-P window position. I just use it's defaults. I believe it only supports `top` and `bottom` window positions. But I may be mistaken.
